pipeline {
    // Agent Maven
    agent {
        node {
            label 'maven'
        }
    }
    // Environment
    environment {
        GIT_COMMIT_SHORT = env.GIT_COMMIT.take(7)
        REPOSITORY = "github.com/marzelwidmer/order-service.git"
        BRANCHES = "[[name: '*/master']]"
        GIT_LAST_COMMIT_MESSAGE = sh(script: "printf \$(git log --pretty='%s (%an)' -1)", returnStdout: true)
        GIT_TAG_MESSAGE = 'ci-release-bot'
        GIT_TAG_USER_EMAIL = "jenkins@c3smonkey.ch"
        GIT_TAG_USER_NAME = "Jenkins"
        DEV_ENVIRONMENT = 'development'
        TEST_ENVIRONMENT = 'testing'
        PROD_ENVIRONMENT = 'production'
        APP_NAME = 'order-service'
    }
    // Stages
    stages {
        // Setup
        stage('Build') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins-ci-user-at-github', usernameVariable: 'USERNAME', passwordVariable: 'TOKEN')]) {
                        git(branches: "$BRANCHES", changelog: true, url: "https://$TOKEN:x-oauth-basic@$REPOSITORY")
                    }
                    // Last Git commit
                    LAST_GIT_COMMIT = sh(
                            script: 'git --no-pager show -s --format=\'%Cblue %h %Creset %s %Cgreen %an %Creset (%ae)\'',
                            returnStdout: true
                    ).trim()
                    sh("chmod +x ./jenkins/ci-semver.sh")
                    // Compute next version
                    NEXT_VERSION = sh(script: "./jenkins/ci-semver.sh", returnStdout: true).trim()
                    echo "Branch: ${env.GIT_BRANCH}"
                    echo "Last Git commit: ${GIT_LAST_COMMIT_MESSAGE}"
                    echo "Last Git commit: ${LAST_GIT_COMMIT}"
                    echo "Last Git commit short: ${GIT_COMMIT_SHORT}"
                    echo "NEXT_VERSION : ${NEXT_VERSION}"
                    sh("./mvnw package -DskipTests -Djgitver.use-version=$NEXT_VERSION")
                }
            }
        }
        // Test and archive artifacts
        stage('Test and Tag') {
            steps {
                echo "run tests"
                sh("./mvnw test")
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    archiveArtifacts artifacts: 'target/**/changelog.*,target/**/*.jar', fingerprint: true, onlyIfSuccessful: true
                }
                success {
                    script {
                        echo "Create tag with version: ${NEXT_VERSION}"
                        sh("""
                        git config --global user.email '${GIT_TAG_USER_EMAIL}'
                        git config --global user.name '${GIT_TAG_USER_NAME}'

                        if [ \$(git tag -l $NEXT_VERSION) ]; then
                            echo tag exist already
                        else    
                            git tag -a -m '${GIT_TAG_MESSAGE}' ${NEXT_VERSION}
                            git push --follow-tags
                        fi
                    """)
                    }
                }
            }
        }
        // Dev Deployment
        stage('Deployment (dev)') {
            steps {
                sh("./mvnw fabric8:deploy -DskipTests -Dfabric8.namespace=development -Djgitver.use-version=$NEXT_VERSION")
                // Verify Deployment
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            openshiftVerifyDeployment(namespace: DEV_ENVIRONMENT,
                                    depCfg: APP_NAME,
                                    replicaCount: '1',
                                    verifyReplicaCount: 'true',
                                    waitTime: '300000')
                        }
                    }
                }
            }
        }
    }
}
