apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

commonLabels:
  env: prod

commonAnnotations:
  component: fsl-backend

images:
- name: docker-registry.default.svc:5000/myproject/demo
  newName: docker-registry.default.svc:5000/prod/order-service
  newTag: latest

resources:
- ../../base/

patchesStrategicMerge:
  - memorylimit_patch.yaml