apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: catalog-service
          resources:
            requests:
              memory: 256M
              cpu: 2000m
            limits:
              memory: 512M
              cpu: 4000m
          env:
            - name: MEM_TOTAL_MB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory

