apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  env: dev

commonAnnotations:
  component: fsl-backend

images:
- name: docker-registry.default.svc:5000/myproject/demo
  newName: docker-registry.default.svc:5000/dev/order-service
  newTag: latest

resources:
- ../../base/
- route.yaml

